
create_clock -name dco_clk -period 1500 -waveform {0 750} [get_ports dco_clk]
set_clock_latency  -source -early -rise 150 [get_clocks dco_clk]
set_clock_latency  -source -early -fall 151 [get_clocks dco_clk]
set_clock_latency  -source -late -rise 152 [get_clocks dco_clk]
set_clock_latency  -source -late -fall 153 [get_clocks dco_clk]
set_clock_transition -rise -min 154 [get_clocks dco_clk]
set_clock_transition -fall -min 155 [get_clocks dco_clk]
set_clock_transition -rise -max 156 [get_clocks dco_clk]
set_clock_transition -fall -max 157 [get_clocks dco_clk]
create_clock -name lfxt_clk -period 1600 -waveform {0 960} [get_ports lfxt_clk]
set_clock_latency  -source -early -rise 151 [get_clocks lfxt_clk]
set_clock_latency  -source -early -fall 152 [get_clocks lfxt_clk]
set_clock_latency  -source -late -rise 153 [get_clocks lfxt_clk]
set_clock_latency  -source -late -fall 154 [get_clocks lfxt_clk]
set_clock_transition -rise -min 155 [get_clocks lfxt_clk]
set_clock_transition -fall -min 156 [get_clocks lfxt_clk]
set_clock_transition -rise -max 157 [get_clocks lfxt_clk]
set_clock_transition -fall -max 158 [get_clocks lfxt_clk]
set_input_delay -clock  yet_to_decide1 -min -rise  100 [get_ports cpu_en]
set_input_delay -clock  yet_to_decide1 -min -fall  101 [get_ports cpu_en]
set_input_delay -clock  yet_to_decide1 -max -rise  102 [get_ports cpu_en]
set_input_delay -clock  yet_to_decide1 -max -fall  103 [get_ports cpu_en]
set_input_transition -clock  yet_to_decide1 -min -rise  150 [get_ports cpu_en]
set_input_transition -clock  yet_to_decide1 -min -fall  151 [get_ports cpu_en]
set_input_transition -clock  yet_to_decide1 -max -rise  152 [get_ports cpu_en]
set_input_transition -clock  yet_to_decide1 -max -fall  153 [get_ports cpu_en]
set_input_delay -clock  yet_to_decide2 -min -rise  101 [get_ports dbg_en]
set_input_delay -clock  yet_to_decide2 -min -fall  102 [get_ports dbg_en]
set_input_delay -clock  yet_to_decide2 -max -rise  103 [get_ports dbg_en]
set_input_delay -clock  yet_to_decide2 -max -fall  104 [get_ports dbg_en]
set_input_transition -clock  yet_to_decide2 -min -rise  151 [get_ports dbg_en]
set_input_transition -clock  yet_to_decide2 -min -fall  152 [get_ports dbg_en]
set_input_transition -clock  yet_to_decide2 -max -rise  153 [get_ports dbg_en]
set_input_transition -clock  yet_to_decide2 -max -fall  154 [get_ports dbg_en]
set_input_delay -clock  yet_to_decide3 -min -rise  102 [get_ports dbg_i2c_addr*]
set_input_delay -clock  yet_to_decide3 -min -fall  103 [get_ports dbg_i2c_addr*]
set_input_delay -clock  yet_to_decide3 -max -rise  104 [get_ports dbg_i2c_addr*]
set_input_delay -clock  yet_to_decide3 -max -fall  105 [get_ports dbg_i2c_addr*]
set_input_transition -clock  yet_to_decide3 -min -rise  152 [get_ports dbg_i2c_addr*]
set_input_transition -clock  yet_to_decide3 -min -fall  153 [get_ports dbg_i2c_addr*]
set_input_transition -clock  yet_to_decide3 -max -rise  154 [get_ports dbg_i2c_addr*]
set_input_transition -clock  yet_to_decide3 -max -fall  155 [get_ports dbg_i2c_addr*]
set_input_delay -clock  yet_to_decide4 -min -rise  103 [get_ports dbg_i2c_broadcast*]
set_input_delay -clock  yet_to_decide4 -min -fall  104 [get_ports dbg_i2c_broadcast*]
set_input_delay -clock  yet_to_decide4 -max -rise  105 [get_ports dbg_i2c_broadcast*]
set_input_delay -clock  yet_to_decide4 -max -fall  106 [get_ports dbg_i2c_broadcast*]
set_input_transition -clock  yet_to_decide4 -min -rise  153 [get_ports dbg_i2c_broadcast*]
set_input_transition -clock  yet_to_decide4 -min -fall  154 [get_ports dbg_i2c_broadcast*]
set_input_transition -clock  yet_to_decide4 -max -rise  155 [get_ports dbg_i2c_broadcast*]
set_input_transition -clock  yet_to_decide4 -max -fall  156 [get_ports dbg_i2c_broadcast*]
set_input_delay -clock  yet_to_decide5 -min -rise  104 [get_ports dbg_i2c_scl]
set_input_delay -clock  yet_to_decide5 -min -fall  105 [get_ports dbg_i2c_scl]
set_input_delay -clock  yet_to_decide5 -max -rise  106 [get_ports dbg_i2c_scl]
set_input_delay -clock  yet_to_decide5 -max -fall  107 [get_ports dbg_i2c_scl]
set_input_transition -clock  yet_to_decide5 -min -rise  154 [get_ports dbg_i2c_scl]
set_input_transition -clock  yet_to_decide5 -min -fall  155 [get_ports dbg_i2c_scl]
set_input_transition -clock  yet_to_decide5 -max -rise  156 [get_ports dbg_i2c_scl]
set_input_transition -clock  yet_to_decide5 -max -fall  157 [get_ports dbg_i2c_scl]
set_input_delay -clock  yet_to_decide6 -min -rise  105 [get_ports dbg_i2c_sda_in]
set_input_delay -clock  yet_to_decide6 -min -fall  106 [get_ports dbg_i2c_sda_in]
set_input_delay -clock  yet_to_decide6 -max -rise  107 [get_ports dbg_i2c_sda_in]
set_input_delay -clock  yet_to_decide6 -max -fall  108 [get_ports dbg_i2c_sda_in]
set_input_transition -clock  yet_to_decide6 -min -rise  155 [get_ports dbg_i2c_sda_in]
set_input_transition -clock  yet_to_decide6 -min -fall  156 [get_ports dbg_i2c_sda_in]
set_input_transition -clock  yet_to_decide6 -max -rise  157 [get_ports dbg_i2c_sda_in]
set_input_transition -clock  yet_to_decide6 -max -fall  158 [get_ports dbg_i2c_sda_in]
set_input_delay -clock  yet_to_decide7 -min -rise  106 [get_ports dbg_uart_rxd]
set_input_delay -clock  yet_to_decide7 -min -fall  107 [get_ports dbg_uart_rxd]
set_input_delay -clock  yet_to_decide7 -max -rise  108 [get_ports dbg_uart_rxd]
set_input_delay -clock  yet_to_decide7 -max -fall  109 [get_ports dbg_uart_rxd]
set_input_transition -clock  yet_to_decide7 -min -rise  156 [get_ports dbg_uart_rxd]
set_input_transition -clock  yet_to_decide7 -min -fall  157 [get_ports dbg_uart_rxd]
set_input_transition -clock  yet_to_decide7 -max -rise  158 [get_ports dbg_uart_rxd]
set_input_transition -clock  yet_to_decide7 -max -fall  159 [get_ports dbg_uart_rxd]
set_input_delay -clock  yet_to_decide8 -min -rise  108 [get_ports dmem_dout*]
set_input_delay -clock  yet_to_decide8 -min -fall  109 [get_ports dmem_dout*]
set_input_delay -clock  yet_to_decide8 -max -rise  110 [get_ports dmem_dout*]
set_input_delay -clock  yet_to_decide8 -max -fall  111 [get_ports dmem_dout*]
set_input_transition -clock  yet_to_decide8 -min -rise  158 [get_ports dmem_dout*]
set_input_transition -clock  yet_to_decide8 -min -fall  159 [get_ports dmem_dout*]
set_input_transition -clock  yet_to_decide8 -max -rise  160 [get_ports dmem_dout*]
set_input_transition -clock  yet_to_decide8 -max -fall  161 [get_ports dmem_dout*]
set_input_delay -clock  yet_to_decide9 -min -rise  109 [get_ports irq*]
set_input_delay -clock  yet_to_decide9 -min -fall  110 [get_ports irq*]
set_input_delay -clock  yet_to_decide9 -max -rise  111 [get_ports irq*]
set_input_delay -clock  yet_to_decide9 -max -fall  112 [get_ports irq*]
set_input_transition -clock  yet_to_decide9 -min -rise  159 [get_ports irq*]
set_input_transition -clock  yet_to_decide9 -min -fall  160 [get_ports irq*]
set_input_transition -clock  yet_to_decide9 -max -rise  161 [get_ports irq*]
set_input_transition -clock  yet_to_decide9 -max -fall  162 [get_ports irq*]
set_input_delay -clock  yet_to_decide10 -min -rise  111 [get_ports dma_addr*]
set_input_delay -clock  yet_to_decide10 -min -fall  112 [get_ports dma_addr*]
set_input_delay -clock  yet_to_decide10 -max -rise  113 [get_ports dma_addr*]
set_input_delay -clock  yet_to_decide10 -max -fall  114 [get_ports dma_addr*]
set_input_transition -clock  yet_to_decide10 -min -rise  161 [get_ports dma_addr*]
set_input_transition -clock  yet_to_decide10 -min -fall  162 [get_ports dma_addr*]
set_input_transition -clock  yet_to_decide10 -max -rise  163 [get_ports dma_addr*]
set_input_transition -clock  yet_to_decide10 -max -fall  164 [get_ports dma_addr*]
set_input_delay -clock  yet_to_decide11 -min -rise  112 [get_ports dma_din*]
set_input_delay -clock  yet_to_decide11 -min -fall  113 [get_ports dma_din*]
set_input_delay -clock  yet_to_decide11 -max -rise  114 [get_ports dma_din*]
set_input_delay -clock  yet_to_decide11 -max -fall  115 [get_ports dma_din*]
set_input_transition -clock  yet_to_decide11 -min -rise  162 [get_ports dma_din*]
set_input_transition -clock  yet_to_decide11 -min -fall  163 [get_ports dma_din*]
set_input_transition -clock  yet_to_decide11 -max -rise  164 [get_ports dma_din*]
set_input_transition -clock  yet_to_decide11 -max -fall  165 [get_ports dma_din*]
set_input_delay -clock  yet_to_decide12 -min -rise  113 [get_ports dma_en]
set_input_delay -clock  yet_to_decide12 -min -fall  114 [get_ports dma_en]
set_input_delay -clock  yet_to_decide12 -max -rise  115 [get_ports dma_en]
set_input_delay -clock  yet_to_decide12 -max -fall  116 [get_ports dma_en]
set_input_transition -clock  yet_to_decide12 -min -rise  163 [get_ports dma_en]
set_input_transition -clock  yet_to_decide12 -min -fall  164 [get_ports dma_en]
set_input_transition -clock  yet_to_decide12 -max -rise  165 [get_ports dma_en]
set_input_transition -clock  yet_to_decide12 -max -fall  166 [get_ports dma_en]
set_input_delay -clock  yet_to_decide13 -min -rise  114 [get_ports dma_priority]
set_input_delay -clock  yet_to_decide13 -min -fall  115 [get_ports dma_priority]
set_input_delay -clock  yet_to_decide13 -max -rise  116 [get_ports dma_priority]
set_input_delay -clock  yet_to_decide13 -max -fall  117 [get_ports dma_priority]
set_input_transition -clock  yet_to_decide13 -min -rise  164 [get_ports dma_priority]
set_input_transition -clock  yet_to_decide13 -min -fall  165 [get_ports dma_priority]
set_input_transition -clock  yet_to_decide13 -max -rise  166 [get_ports dma_priority]
set_input_transition -clock  yet_to_decide13 -max -fall  167 [get_ports dma_priority]
set_input_delay -clock  yet_to_decide14 -min -rise  115 [get_ports dma_we*]
set_input_delay -clock  yet_to_decide14 -min -fall  116 [get_ports dma_we*]
set_input_delay -clock  yet_to_decide14 -max -rise  117 [get_ports dma_we*]
set_input_delay -clock  yet_to_decide14 -max -fall  118 [get_ports dma_we*]
set_input_transition -clock  yet_to_decide14 -min -rise  165 [get_ports dma_we*]
set_input_transition -clock  yet_to_decide14 -min -fall  166 [get_ports dma_we*]
set_input_transition -clock  yet_to_decide14 -max -rise  167 [get_ports dma_we*]
set_input_transition -clock  yet_to_decide14 -max -fall  168 [get_ports dma_we*]
set_input_delay -clock  yet_to_decide15 -min -rise  116 [get_ports dma_wkup]
set_input_delay -clock  yet_to_decide15 -min -fall  117 [get_ports dma_wkup]
set_input_delay -clock  yet_to_decide15 -max -rise  118 [get_ports dma_wkup]
set_input_delay -clock  yet_to_decide15 -max -fall  119 [get_ports dma_wkup]
set_input_transition -clock  yet_to_decide15 -min -rise  166 [get_ports dma_wkup]
set_input_transition -clock  yet_to_decide15 -min -fall  167 [get_ports dma_wkup]
set_input_transition -clock  yet_to_decide15 -max -rise  168 [get_ports dma_wkup]
set_input_transition -clock  yet_to_decide15 -max -fall  169 [get_ports dma_wkup]
set_input_delay -clock  yet_to_decide16 -min -rise  117 [get_ports nmi]
set_input_delay -clock  yet_to_decide16 -min -fall  118 [get_ports nmi]
set_input_delay -clock  yet_to_decide16 -max -rise  119 [get_ports nmi]
set_input_delay -clock  yet_to_decide16 -max -fall  120 [get_ports nmi]
set_input_transition -clock  yet_to_decide16 -min -rise  167 [get_ports nmi]
set_input_transition -clock  yet_to_decide16 -min -fall  168 [get_ports nmi]
set_input_transition -clock  yet_to_decide16 -max -rise  169 [get_ports nmi]
set_input_transition -clock  yet_to_decide16 -max -fall  170 [get_ports nmi]
set_input_delay -clock  yet_to_decide17 -min -rise  118 [get_ports per_dout*]
set_input_delay -clock  yet_to_decide17 -min -fall  119 [get_ports per_dout*]
set_input_delay -clock  yet_to_decide17 -max -rise  120 [get_ports per_dout*]
set_input_delay -clock  yet_to_decide17 -max -fall  121 [get_ports per_dout*]
set_input_transition -clock  yet_to_decide17 -min -rise  168 [get_ports per_dout*]
set_input_transition -clock  yet_to_decide17 -min -fall  169 [get_ports per_dout*]
set_input_transition -clock  yet_to_decide17 -max -rise  170 [get_ports per_dout*]
set_input_transition -clock  yet_to_decide17 -max -fall  171 [get_ports per_dout*]
set_input_delay -clock  yet_to_decide18 -min -rise  119 [get_ports pmem_dout*]
set_input_delay -clock  yet_to_decide18 -min -fall  120 [get_ports pmem_dout*]
set_input_delay -clock  yet_to_decide18 -max -rise  121 [get_ports pmem_dout*]
set_input_delay -clock  yet_to_decide18 -max -fall  122 [get_ports pmem_dout*]
set_input_transition -clock  yet_to_decide18 -min -rise  169 [get_ports pmem_dout*]
set_input_transition -clock  yet_to_decide18 -min -fall  170 [get_ports pmem_dout*]
set_input_transition -clock  yet_to_decide18 -max -rise  171 [get_ports pmem_dout*]
set_input_transition -clock  yet_to_decide18 -max -fall  172 [get_ports pmem_dout*]
set_input_delay -clock  yet_to_decide19 -min -rise  120 [get_ports reset_n]
set_input_delay -clock  yet_to_decide19 -min -fall  121 [get_ports reset_n]
set_input_delay -clock  yet_to_decide19 -max -rise  122 [get_ports reset_n]
set_input_delay -clock  yet_to_decide19 -max -fall  123 [get_ports reset_n]
set_input_transition -clock  yet_to_decide19 -min -rise  170 [get_ports reset_n]
set_input_transition -clock  yet_to_decide19 -min -fall  171 [get_ports reset_n]
set_input_transition -clock  yet_to_decide19 -max -rise  172 [get_ports reset_n]
set_input_transition -clock  yet_to_decide19 -max -fall  173 [get_ports reset_n]
set_input_delay -clock  yet_to_decide20 -min -rise  121 [get_ports scan_enable]
set_input_delay -clock  yet_to_decide20 -min -fall  122 [get_ports scan_enable]
set_input_delay -clock  yet_to_decide20 -max -rise  123 [get_ports scan_enable]
set_input_delay -clock  yet_to_decide20 -max -fall  124 [get_ports scan_enable]
set_input_transition -clock  yet_to_decide20 -min -rise  171 [get_ports scan_enable]
set_input_transition -clock  yet_to_decide20 -min -fall  172 [get_ports scan_enable]
set_input_transition -clock  yet_to_decide20 -max -rise  173 [get_ports scan_enable]
set_input_transition -clock  yet_to_decide20 -max -fall  174 [get_ports scan_enable]
set_input_delay -clock  yet_to_decide21 -min -rise  122 [get_ports scan_mode]
set_input_delay -clock  yet_to_decide21 -min -fall  123 [get_ports scan_mode]
set_input_delay -clock  yet_to_decide21 -max -rise  124 [get_ports scan_mode]
set_input_delay -clock  yet_to_decide21 -max -fall  125 [get_ports scan_mode]
set_input_transition -clock  yet_to_decide21 -min -rise  172 [get_ports scan_mode]
set_input_transition -clock  yet_to_decide21 -min -fall  173 [get_ports scan_mode]
set_input_transition -clock  yet_to_decide21 -max -rise  174 [get_ports scan_mode]
set_input_transition -clock  yet_to_decide21 -max -fall  175 [get_ports scan_mode]
set_output_delay -clock  yet_to_decide22 -min -rise  100 [get_ports aclk]
set_output_delay -clock  yet_to_decide22 -min -fall  101 [get_ports aclk]
set_output_delay -clock  yet_to_decide22 -max -rise  102 [get_ports aclk]
set_output_delay -clock  yet_to_decide22 -max -fall  103 [get_ports aclk]
set_load 10 [get_ports aclk]
set_output_delay -clock  yet_to_decide23 -min -rise  101 [get_ports aclk_en]
set_output_delay -clock  yet_to_decide23 -min -fall  102 [get_ports aclk_en]
set_output_delay -clock  yet_to_decide23 -max -rise  103 [get_ports aclk_en]
set_output_delay -clock  yet_to_decide23 -max -fall  104 [get_ports aclk_en]
set_load 11 [get_ports aclk_en]
set_output_delay -clock  yet_to_decide24 -min -rise  102 [get_ports dbg_freeze]
set_output_delay -clock  yet_to_decide24 -min -fall  103 [get_ports dbg_freeze]
set_output_delay -clock  yet_to_decide24 -max -rise  104 [get_ports dbg_freeze]
set_output_delay -clock  yet_to_decide24 -max -fall  105 [get_ports dbg_freeze]
set_load 12 [get_ports dbg_freeze]
set_output_delay -clock  yet_to_decide25 -min -rise  103 [get_ports dbg_i2c_sda_out]
set_output_delay -clock  yet_to_decide25 -min -fall  104 [get_ports dbg_i2c_sda_out]
set_output_delay -clock  yet_to_decide25 -max -rise  105 [get_ports dbg_i2c_sda_out]
set_output_delay -clock  yet_to_decide25 -max -fall  106 [get_ports dbg_i2c_sda_out]
set_load 13 [get_ports dbg_i2c_sda_out]
set_output_delay -clock  yet_to_decide26 -min -rise  104 [get_ports dbg_uart_txd]
set_output_delay -clock  yet_to_decide26 -min -fall  105 [get_ports dbg_uart_txd]
set_output_delay -clock  yet_to_decide26 -max -rise  106 [get_ports dbg_uart_txd]
set_output_delay -clock  yet_to_decide26 -max -fall  107 [get_ports dbg_uart_txd]
set_load 14 [get_ports dbg_uart_txd]
set_output_delay -clock  yet_to_decide27 -min -rise  105 [get_ports dco_enable]
set_output_delay -clock  yet_to_decide27 -min -fall  106 [get_ports dco_enable]
set_output_delay -clock  yet_to_decide27 -max -rise  107 [get_ports dco_enable]
set_output_delay -clock  yet_to_decide27 -max -fall  108 [get_ports dco_enable]
set_load 15 [get_ports dco_enable]
set_output_delay -clock  yet_to_decide28 -min -rise  106 [get_ports dco_wkup]
set_output_delay -clock  yet_to_decide28 -min -fall  107 [get_ports dco_wkup]
set_output_delay -clock  yet_to_decide28 -max -rise  108 [get_ports dco_wkup]
set_output_delay -clock  yet_to_decide28 -max -fall  109 [get_ports dco_wkup]
set_load 16 [get_ports dco_wkup]
set_output_delay -clock  yet_to_decide29 -min -rise  107 [get_ports dmem_addr]
set_output_delay -clock  yet_to_decide29 -min -fall  108 [get_ports dmem_addr]
set_output_delay -clock  yet_to_decide29 -max -rise  109 [get_ports dmem_addr]
set_output_delay -clock  yet_to_decide29 -max -fall  110 [get_ports dmem_addr]
set_load 17 [get_ports dmem_addr]
set_output_delay -clock  yet_to_decide30 -min -rise  108 [get_ports dmem_cen]
set_output_delay -clock  yet_to_decide30 -min -fall  109 [get_ports dmem_cen]
set_output_delay -clock  yet_to_decide30 -max -rise  110 [get_ports dmem_cen]
set_output_delay -clock  yet_to_decide30 -max -fall  111 [get_ports dmem_cen]
set_load 18 [get_ports dmem_cen]
set_output_delay -clock  yet_to_decide31 -min -rise  109 [get_ports dmem_din]
set_output_delay -clock  yet_to_decide31 -min -fall  110 [get_ports dmem_din]
set_output_delay -clock  yet_to_decide31 -max -rise  111 [get_ports dmem_din]
set_output_delay -clock  yet_to_decide31 -max -fall  112 [get_ports dmem_din]
set_load 19 [get_ports dmem_din]
set_output_delay -clock  yet_to_decide32 -min -rise  110 [get_ports dmem_wen]
set_output_delay -clock  yet_to_decide32 -min -fall  111 [get_ports dmem_wen]
set_output_delay -clock  yet_to_decide32 -max -rise  112 [get_ports dmem_wen]
set_output_delay -clock  yet_to_decide32 -max -fall  113 [get_ports dmem_wen]
set_load 20 [get_ports dmem_wen]
set_output_delay -clock  yet_to_decide33 -min -rise  111 [get_ports irq_acc]
set_output_delay -clock  yet_to_decide33 -min -fall  112 [get_ports irq_acc]
set_output_delay -clock  yet_to_decide33 -max -rise  113 [get_ports irq_acc]
set_output_delay -clock  yet_to_decide33 -max -fall  114 [get_ports irq_acc]
set_load 21 [get_ports irq_acc]
set_output_delay -clock  yet_to_decide34 -min -rise  112 [get_ports lfxt_enable]
set_output_delay -clock  yet_to_decide34 -min -fall  113 [get_ports lfxt_enable]
set_output_delay -clock  yet_to_decide34 -max -rise  114 [get_ports lfxt_enable]
set_output_delay -clock  yet_to_decide34 -max -fall  115 [get_ports lfxt_enable]
set_load 22 [get_ports lfxt_enable]
set_output_delay -clock  yet_to_decide35 -min -rise  113 [get_ports lfxt_wkup]
set_output_delay -clock  yet_to_decide35 -min -fall  114 [get_ports lfxt_wkup]
set_output_delay -clock  yet_to_decide35 -max -rise  115 [get_ports lfxt_wkup]
set_output_delay -clock  yet_to_decide35 -max -fall  116 [get_ports lfxt_wkup]
set_load 23 [get_ports lfxt_wkup]
set_output_delay -clock  yet_to_decide36 -min -rise  114 [get_ports mclk]
set_output_delay -clock  yet_to_decide36 -min -fall  115 [get_ports mclk]
set_output_delay -clock  yet_to_decide36 -max -rise  116 [get_ports mclk]
set_output_delay -clock  yet_to_decide36 -max -fall  117 [get_ports mclk]
set_load 24 [get_ports mclk]
set_output_delay -clock  yet_to_decide37 -min -rise  115 [get_ports dma_dout]
set_output_delay -clock  yet_to_decide37 -min -fall  116 [get_ports dma_dout]
set_output_delay -clock  yet_to_decide37 -max -rise  117 [get_ports dma_dout]
set_output_delay -clock  yet_to_decide37 -max -fall  118 [get_ports dma_dout]
set_load 25 [get_ports dma_dout]
set_output_delay -clock  yet_to_decide38 -min -rise  116 [get_ports dma_ready]
set_output_delay -clock  yet_to_decide38 -min -fall  117 [get_ports dma_ready]
set_output_delay -clock  yet_to_decide38 -max -rise  118 [get_ports dma_ready]
set_output_delay -clock  yet_to_decide38 -max -fall  119 [get_ports dma_ready]
set_load 26 [get_ports dma_ready]
set_output_delay -clock  yet_to_decide39 -min -rise  117 [get_ports dma_resp]
set_output_delay -clock  yet_to_decide39 -min -fall  118 [get_ports dma_resp]
set_output_delay -clock  yet_to_decide39 -max -rise  119 [get_ports dma_resp]
set_output_delay -clock  yet_to_decide39 -max -fall  120 [get_ports dma_resp]
set_load 27 [get_ports dma_resp]
set_output_delay -clock  yet_to_decide40 -min -rise  118 [get_ports per_addr*]
set_output_delay -clock  yet_to_decide40 -min -fall  119 [get_ports per_addr*]
set_output_delay -clock  yet_to_decide40 -max -rise  120 [get_ports per_addr*]
set_output_delay -clock  yet_to_decide40 -max -fall  121 [get_ports per_addr*]
set_load 28 [get_ports per_addr*]
set_output_delay -clock  yet_to_decide41 -min -rise  119 [get_ports per_din*]
set_output_delay -clock  yet_to_decide41 -min -fall  120 [get_ports per_din*]
set_output_delay -clock  yet_to_decide41 -max -rise  121 [get_ports per_din*]
set_output_delay -clock  yet_to_decide41 -max -fall  122 [get_ports per_din*]
set_load 29 [get_ports per_din*]
set_output_delay -clock  yet_to_decide42 -min -rise  120 [get_ports per_en]
set_output_delay -clock  yet_to_decide42 -min -fall  121 [get_ports per_en]
set_output_delay -clock  yet_to_decide42 -max -rise  122 [get_ports per_en]
set_output_delay -clock  yet_to_decide42 -max -fall  123 [get_ports per_en]
set_load 30 [get_ports per_en]
set_output_delay -clock  yet_to_decide43 -min -rise  121 [get_ports per_we*]
set_output_delay -clock  yet_to_decide43 -min -fall  122 [get_ports per_we*]
set_output_delay -clock  yet_to_decide43 -max -rise  123 [get_ports per_we*]
set_output_delay -clock  yet_to_decide43 -max -fall  124 [get_ports per_we*]
set_load 31 [get_ports per_we*]
set_output_delay -clock  yet_to_decide44 -min -rise  122 [get_ports pmem_addr]
set_output_delay -clock  yet_to_decide44 -min -fall  123 [get_ports pmem_addr]
set_output_delay -clock  yet_to_decide44 -max -rise  124 [get_ports pmem_addr]
set_output_delay -clock  yet_to_decide44 -max -fall  125 [get_ports pmem_addr]
set_load 32 [get_ports pmem_addr]
set_output_delay -clock  yet_to_decide45 -min -rise  123 [get_ports pmem_cen]
set_output_delay -clock  yet_to_decide45 -min -fall  124 [get_ports pmem_cen]
set_output_delay -clock  yet_to_decide45 -max -rise  125 [get_ports pmem_cen]
set_output_delay -clock  yet_to_decide45 -max -fall  126 [get_ports pmem_cen]
set_load 33 [get_ports pmem_cen]
set_output_delay -clock  yet_to_decide46 -min -rise  124 [get_ports pmem_din]
set_output_delay -clock  yet_to_decide46 -min -fall  125 [get_ports pmem_din]
set_output_delay -clock  yet_to_decide46 -max -rise  126 [get_ports pmem_din]
set_output_delay -clock  yet_to_decide46 -max -fall  127 [get_ports pmem_din]
set_load 34 [get_ports pmem_din]
set_output_delay -clock  yet_to_decide47 -min -rise  125 [get_ports pmem_wen]
set_output_delay -clock  yet_to_decide47 -min -fall  126 [get_ports pmem_wen]
set_output_delay -clock  yet_to_decide47 -max -rise  127 [get_ports pmem_wen]
set_output_delay -clock  yet_to_decide47 -max -fall  128 [get_ports pmem_wen]
set_load 35 [get_ports pmem_wen]
set_output_delay -clock  yet_to_decide48 -min -rise  126 [get_ports puc_rst]
set_output_delay -clock  yet_to_decide48 -min -fall  127 [get_ports puc_rst]
set_output_delay -clock  yet_to_decide48 -max -rise  128 [get_ports puc_rst]
set_output_delay -clock  yet_to_decide48 -max -fall  129 [get_ports puc_rst]
set_load 36 [get_ports puc_rst]
set_output_delay -clock  yet_to_decide49 -min -rise  127 [get_ports smclk]
set_output_delay -clock  yet_to_decide49 -min -fall  128 [get_ports smclk]
set_output_delay -clock  yet_to_decide49 -max -rise  129 [get_ports smclk]
set_output_delay -clock  yet_to_decide49 -max -fall  130 [get_ports smclk]
set_load 37 [get_ports smclk]
set_output_delay -clock  yet_to_decide50 -min -rise  128 [get_ports smclk_en]
set_output_delay -clock  yet_to_decide50 -min -fall  129 [get_ports smclk_en]
set_output_delay -clock  yet_to_decide50 -max -rise  130 [get_ports smclk_en]
set_output_delay -clock  yet_to_decide50 -max -fall  131 [get_ports smclk_en]
set_load 38 [get_ports smclk_en]